周一:
  启用: True
  type: 自定义 
  开始时间: 9
  持续小时数: 13
周二:
  启用: True
  type: 自定义 
  开始时间: 9
  持续小时数: 13
周三:
  启用: True
  type: 自定义 
  开始时间: 9
  持续小时数: 13
周四:
  启用: True
  type: 自定义 
  开始时间: 9
  持续小时数: 13
周五:
  启用: True
  type: 自定义 
  开始时间: 9
  持续小时数: 13
周六:
  启用: True
  type: 自定义 
  开始时间: 9
  持续小时数: 13
周日:
  启用: True
  type: 自定义 
  开始时间: 9
  持续小时数: 13

自定义:
    - 58604
# 3东：42101-42140
# 3西：42141-42184
# 3北: 42185-42215
# 5： 43285-43455 （包括但不仅限于，json包懒得看，以下同理（（（（）
# 7： 42587-42700
# 8： 42710-42842
# 9： 42887-42978
# 10：43031-43114
# 11：43153-43266

target: https://hdu.huitu.zhishulib.com/Seat/Index/bookSeats?LAB_JSON=1
start-time: 1970-01-01 08:00:00
headers:
  Host: hdu.huitu.zhishulib.com
  Accept: application/json, text/plain, */*
  User-Agent: Mozilla/5.0 (Linux; Android 11; SM-G9910 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/4375 MMWEBSDK/20221012 Mobile Safari/537.36 MMWEBID/5551 MicroMessenger/8.0.30.2260(0x28001E55) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64 miniProgram/wx5e72fc4ec15ca4e8
  Content-Type: application/x-www-form-urlencoded;charset=UTF-8
  Origin: https://hdu.huitu.zhishulib.com
  X-Requested-With: com.tencent.mm
  Sec-Fetch-Site: same-origin
  Sec-Fetch-Mode: cors
  Sec-Fetch-Dest: empty
  Referer: https://hdu.huitu.zhishulib.com/content/index/startUp/openid/okOhQt-6kvozwqD9JhY_A4_8nXEQ/
  Accept-Encoding: gzip, deflate
  Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
  Connection: close
